name: Build Dylib

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Tweak
        run: |
          make FINALPACKAGE=1

      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: PaopaoArabic-Dylib
          path: |
            .theos/obj/debug/*.dylib
            obj/*.dylib
